language: c
before_install:
  - sudo apt-get install -y valgrind
script:
  - make
  - make test_valg
  - make clean
  - chmod +x ./validate_example.sh
  - ./validate_example.sh
  - make cov

after_success:
  - bash <(curl -s https://codecov.io/bash)