language: c
before_install:
  - sudo apt-get install -y valgrind
script:
  - make vg
  # Validate example
  - make -C example/
  - example/example > out.txt
  - fgrep "x: 100, y: 200" out.txt
  - fgrep "x: 300, y: 400" out.txt
  - (( `cat out.txt | wc -l` == 3 ))

